import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NEXT Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-black text-white h-screen grid place-content-center">
        <h1 className="text-6xl font-bold">NEXT Template</h1>
      </div>
    </div>
  );
};

export default Home;
